// AUTO-GENERATED by scripts/syncSiteConfig.mjs from the Google Sheet.
// Do not edit by hand — changes here are overwritten on the next sync.
// To update content: edit the Google Sheet, then run `npm run sync-config`
// (this also runs automatically before `npm run build`).
export const site = {
  professor: {
    name: "Miryam Elizabeth",
    initials: "ME",
    email: "r.whitfield@example.edu"
  },
  course: {
    code: "Aprendizaje Automatico",
    title: "Aprendizaje Automático",
    term: "Semestre 2026",
    landing: {
      description: "En esta página encontrarás todo el material para tu asignatura. Si te inscribiste tarde, es tu responsabilidad ponerte al día con todo el material del curso (también si faltas o llegas tarde).",
      dates: "31 de agosto al 18 de septiembre 2026",
      horarios: "7 a 10pm",
      ubicacion: "Nuevo Rodin Salón 1"
    },
    overview: {
      objectives: "En esta clase estudiaremos los algoritmos básicos e intermedios del área de Aprendizaje Automático (Machine Learning). Se identificarán diferentes problemas y las técnicas adecuadas para resolverlos desde un punto de vista de análisis de datos.",
      learning: [
        "**RA1.** Explicar los conceptos fundamentales del Aprendizaje Automático y su relación con la Inteligencia Artificial.",
        "**RA2.** Analizar y preparar conjuntos de datos estructurados y no estructurados para problemas de Aprendizaje Automático.",
        "**RA3.** Aplicar algoritmos básicos e intermedios de Aprendizaje Automático supervisado y no supervisado para resolver problemas de regresión, clasificación, y agrupamiento.",
        "**RA4.** Evaluar y comparar modelos de Aprendizaje Automático utilizando métricas adecuadas y técnicas de validación.",
        "**RA5.** Ajustar hiperparámetros y analizar el impacto del sobreajuste, subajuste, sesgo y varianza en el desempeño de los modelos.",
        "**RA6.** Implementar flujos completos de trabajo de Aprendizaje Automático utilizando herramientas de programación en Python.",
        "**RA7.** Analizar implicaciones éticas y sociales del uso de modelos de Aprendizaje Automático."
      ],
      structure: [
        "Introducción al Aprendizaje Automático.",
        "Métodos de Aprendizaje Automático Supervisado",
        "Métodos de Aprendizaje Automático No Supervisado",
        "Herramientas actuales",
        "Visualización",
        "Examen Final y Entrega de Proyectos"
      ],
      evaluation: {
        "15": "2 Tareas",
        "20": "Proyecto Final",
        "25": "Actividades y dinámicas",
        "40": "Examen Final",
        "100": "Total"
      },
      project: {
        resume: "El proyecto final consistirá en la aplicación de una técnica de Machine Learning sobre un conjunto de datos. El proyecto deberá incluir el diseño metodológico del modelo, el proceso de entrenamiento y validación, así como la evaluación de su desempeño mediante métricas adecuadas. Se espera que los estudiantes justifiquen las decisiones tomadas y analicen críticamente los resultados obtenidos.",
        detail: "*<<Más adelante durante el curso se te irán dando las instrucciones.>>*",
        team: "**Modalidad:** Parejas o equipos de 3 personas."
      },
      help: [
        "Antes de la clase (presencial) o agendar cita a través del correo electrónico (mevilla@up.edu.mx).",
        "Al solicitar una cita por favor propón uno o varios rangos de horario en los que tengas disponibilidad. La profesora te responderá oportunamente a través del mismo medio de contacto para confirmarte el horario en que te podrá atender."
      ],
      software: "Los estudiantes necesitarán acceso a una computadora personal con Google Colab(incluido en Google Drive)"
    },
    politics: {
      rules: "Aquí encontrarás el [reglamento general](https://www.up.edu.mx/wp-content/uploads/2024/01/Reglamento_general_Universidad_Panamericana.pdf) de la Universidad Panamericana.",
      activities: [
        "**Entregar las tareas/actividades/etc. puntualmente, NO hay extensiones. ++La inscripción tardía no exime de revisar todo el contenido del curso y entregar las actividades a tiempo (si aplica).++**",
        "No se recibirán tareas/actividades por correo electrónico, a menos que se indique lo contrario. **Deberá ser por los medios indicados.**",
        "Toda las tareas deberán cumplir con los lineamientos de entrega indicados. En caso de no cumplirlos NO serán recibidas (ej. **notebook de Colab, no archivo de Python**)."
      ],
      attendance: [
        "Es obligatorio atender a todas las sesiones. En caso de alguna situación extraordinaria se deberá platicarlo con la profesora.",
        "No se otorgan puntos por asistencia."
      ],
      timing: [
        "Ingresar puntualmente a la sesión de clase. **La tolerancia máxima es de 15 minutos, después de esa hora, se cuenta como falta.**"
      ],
      integrity: [
        "Cualquier tipo de fraude o engaño en cualquier actividad del curso será castigado de acuerdo a las regulaciones de la institución."
      ],
      discipline: [
        "Se debe tener un respeto total al profesor y a los demás compañeros.",
        "Se pueden utilizar teléfonos, siempre y cuando no interfiera con la clase. **Es responsabilidad del alumno prestar atención a la clase.**",
        "**++Guardar silencio durante las explicaciones++**, para facilitar el aprendizaje y por respeto a los demás compañeros del curso."
      ],
      ia: [
        {
          paragraph: "El uso de herramientas de inteligencia artificial generativa **está permitido como herramienta de apoyo, pero no como sustituto del aprendizaje, el análisis o la reflexión personal.** El uso de IA es apropiado para tareas como:"
        },
        {
          list: [
            "Generar ideas iniciales o lluvia de ideas.",
            "Mejorar la redacción, gramática o claridad de un texto.",
            "Explicar conceptos o resolver dudas.",
            "Apoyar el desarrollo de código."
          ]
        },
        {
          paragraph: "Sin embargo, **no es aceptable** entregar como propio **contenido generado íntegramente por IA** cuando la actividad tiene como propósito evaluar el razonamiento, la interpretación, la argumentación, la toma de decisiones o la opinión del estudiante. Esto incluye, entre otros, debates, reflexiones, análisis de casos, conclusiones, respuestas abiertas y cualquier actividad donde se solicite una postura o interpretación personal."
        },
        {
          list: [
            "Si utilizan herramientas de IA generativa en el proceso de elaboración de sus trabajos, se espera que sean **transparentes al respecto.** Pueden indicar cómo la han utilizado (por ejemplo, \"Se utilizó IA para generar ideas iniciales sobre el tema X\" o \"Se empleó IA para revisar la gramática\"). Esta transparencia contribuye a un **ambiente de aprendizaje honesto y abierto.**",
            "Todo contenido generado por IA que se incorpore en una entrega debe ser **revisado, verificado, adaptado e integrado críticamente** por el estudiante. **La entrega de texto generado por IA sin una contribución intelectual propia**, sin revisión o con modificaciones únicamente superficiales será considerada una falta a la integridad académica.",
            "El uso de IA **no exime al estudiante de la responsabilidad sobre su trabajo.** Cada alumno es responsable de la precisión, calidad, originalidad, referencias, funcionamiento del código y veracidad de toda la información presentada, independientemente de las herramientas utilizadas.",
            "La profesora podrá realizar preguntas durante la clase o solicitar explicaciones adicionales sobre cualquier entrega para verificar que el estudiante comprende el contenido presentado y que el trabajo refleja su propio aprendizaje."
          ]
        }
      ]
    },
    classes: [
      {
        id: "tema-1",
        number: 1,
        title: "¿Qué es Aprendizaje Automático?",
        date: "viernes 1 de agosto, 2026",
        objective: "Aprenderás los diferentes tipos de aprendizaje que existen, el proceso de resolución de problemas y la fase de exploración y pre-procesamiento utilizando bibliotecas de Python.",
        material: [
          {
            paragraph: "Aquí puedes descargar las presentaciones y archivos de la clase ⬇️"
          },
          {
            list: [
              "[Tema 2.pdf](https://drive.google.com/file/d/1R-EU3H14e0anUthTsWFvIqa7RIuSTuiu/view?usp=drive_link)",
              "[Material para la dinamica de clase](https://drive.google.com/file/d/1WSkOYVS62I2W30zsy6HLa66PzjsFAVJ7/view?usp=drive_link)",
              "[Google Colab 1](https://colab.research.google.com/drive/1vFyl2R7U9N6MW1tizpb8SDpJ0ROfX8n7?usp=drive_link)",
              "[Google Colab 2](https://colab.research.google.com/drive/1ZJDzLIM93dcAfkKIrpJOHWi1rym_PJsp?usp=drive_link)"
            ]
          }
        ],
        activity: [
          {
            list: [
              "Crea una copia del Google Colab y utilízala para resolver la actividad.",
              "Cambia el siguiente encabezado por **tus datos.**"
            ]
          },
          {
            code: "# -------------------------------------------------------------\n# Actividad 2\n# Fecha: 7 Agosto 2026\n# Equipo:\n#\tÁngela López\n#\tWesley Evers\n# --------------------------------------------------------------"
          },
          {
            list: [
              "Sigue las instrucciones que se describen en el notebook.",
              "Al finalizar entrega tu actividad en el siguiente [formulario de Google](https://forms.gle/RDBp8dmiADf9B5mn9) en un archivo IPYNB, con el nombre **Actividad2_NombreApellido_Nombre_Apellido.ipynb**",
              "**Es necesario iniciar sesión con tu cuenta de correo de la UP.**",
              "**Sólo un miembro del equipo necesita subir el archivo.**",
              "**Al finalizar se envía un acuse de recibo a tu correo. **"
            ]
          },
          {
            paragraph: "**Fecha límite: Viernes 14 de agosto antes de la clase (6:59 p.m.)**"
          }
        ]
      },
      {
        id: "tema-2",
        number: 2,
        title: "Conceptos Básicos",
        date: "viernes 7 de agosto, 2026",
        objective: "Aplicar técnicas de limpieza, transformación y análisis exploratorio de datos como paso previo al entrenamiento de modelos.",
        material: [
          {
            list: [
              "Presentación: Preparación de datos (Colab)",
              "Notebook de ejemplo: limpieza y EDA"
            ]
          }
        ],
        activity: [
          {
            list: [
              "Práctica guiada en Colab: limpieza de un dataset con valores faltantes."
            ]
          }
        ],
        homework: [
          {
            list: [
              "Completar el notebook de limpieza de datos con el dataset asignado."
            ]
          }
        ]
      }
    ],
    grading: [
      {
        label: "Homework",
        percent: 30,
        color: "blue.6"
      },
      {
        label: "Midterm",
        percent: 25,
        color: "blue.4"
      },
      {
        label: "Final",
        percent: 25,
        color: "blue.3"
      },
      {
        label: "Participation",
        percent: 20,
        color: "gray.4"
      }
    ],
    resources: [
      {
        label: "Syllabus (PDF)",
        href: "#",
        icon: "file"
      },
      {
        label: "Lecture slides",
        href: "#",
        icon: "slides"
      },
      {
        label: "Textbook and readings",
        href: "#",
        icon: "book"
      },
      {
        label: "Discussion forum",
        href: "#",
        icon: "forum"
      }
    ]
  }
};
